nginx1:
    image: scorpionis/nginx-geo
    ports:
        - "80:80"
    environment:
        - "constraint:node==swarm-master"    
nginx2:
    image: scorpionis/nginx-geo
    ports:
        - "80:80"
    environment:
        - "constraint:node==swarm-agent-1"
node1:
    image: scorpionis/nodejs
    ports:
        - "8080"
    container_name: "node1"
    environment:
        - "constraint:node==swarm-master"
node2:
    image: scorpionis/nodejs
    ports:
        - "8080"
    container_name: "node2"
    environment:
        - "constraint:node==swarm-agent-1"
redis1:
    image: redis
    ports:
        - "6379"
    container_name: "redis1"
    environment:
        - "constraint:node==swarm-master"
redis2:
    image: redis
    ports:
        - "6379"
    container_name: "redis2"
    environment:
        - "constraint:node==swarm-agent-1"

