redis:
    image: redis
    ports:
        - "6379"
    container_name: "redis"
node1:
    image: scorpionis/nodejs
    ports:
        - "8080"
    container_name: "node1"
    environment:
        - "constraint:node==swarm-agent-1"
node2:
    image: scorpionis/nodejs
    ports:
        - "8080"
    container_name: "node2"
    environment:
        - "constraint:node==swarm-master"    
nginx1:
    image: scorpionis/nginx-geo
    ports:
        - "80:80"
    environment:
        - "constraint:node==swarm-agent-1"    
nginx2:
    image: scorpionis/nginx-geo
    ports:
        - "80:80"
    environment:
        - "constraint:node==swarm-master"
